language: csharp
solution: ImgBbSdk.sln
mono: none
dotnet: 2.1.0-preview1-26216-03

# Before installation.
before_install: true

# Dependency installation phrase.
install:
- dotnet restore ImgBbSdk.sln

# Build phrase.
script:
- dotnet build ImgBbSdk.sln
